/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * game.java
 *
 * Created on Jan 14, 2011, 9:52:38 AM
 */

package pjp;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author DOC
 */
public class game extends javax.swing.JFrame {

    /** Creates new form game */
    public game() {
        initComponents();

       

        lblT1.setVisible(true);
       lblT2.setVisible(true);
       lblT3.setVisible(true);
       back.setVisible(true);
       lblTank.setVisible(true);

        new Thread(new Runnable() {

            public void run() {
                for(int i=lblT1.getX();i<getWidth()-lblT1.getWidth();i--){
                    lblT1.setLocation(i, lblT1.getY());
                    try {
                        Thread.sleep(175);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(game.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }).start();


        new Thread(new Runnable() {

            public void run() {
                for(int t2=lblT2.getX();t2<getWidth();t2--){
                    lblT2.setLocation(t2,lblT2.getY());
                    try {
                        Thread.sleep(120);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(game.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }).start();


      /*  new Thread(new Runnable() {

            public void run() {
                for(int s=jLabel1.getX();s<getWidth();s--){
                    lblT2.setLocation(s,lblT2.getY());
                    try {
                        Thread.sleep(20);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(game.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }).start();

         new Thread(new Runnable() {

            public void run() {
                for(int s=jLabel1.getY();s<getHeight();s++){
                    lblT2.setLocation(jLabel1.getX(),s);
                    try {
                        Thread.sleep(20);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(game.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }).start(); */

        new Thread(new Runnable() {

            public void run() {
                for(int t3=getX();t3<getWidth();t3++){
                    lblT3.setLocation(t3,lblT3.getY());
                    try {
                        Thread.sleep(175);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(game.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }
            }
        }).start();

      
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTank = new javax.swing.JLabel();
        lblbullet = new javax.swing.JLabel();
        lblT1 = new javax.swing.JLabel();
        lblT3 = new javax.swing.JLabel();
        lblT2 = new javax.swing.JLabel();
        lblBullet1 = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tank");
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTank.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pjp/images/SU082-09.jpg"))); // NOI18N
        getContentPane().add(lblTank, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 600, 200, 80));

        lblbullet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pjp/images/Untitled.jpg"))); // NOI18N
        getContentPane().add(lblbullet, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 650, 10, 10));

        lblT1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pjp/images/tank.jpg"))); // NOI18N
        getContentPane().add(lblT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, 220, 110));

        lblT3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pjp/images/tank2.jpg"))); // NOI18N
        getContentPane().add(lblT3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 180, 100));

        lblT2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pjp/images/tank3.jpg"))); // NOI18N
        getContentPane().add(lblT2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 120, 220, 100));

        lblBullet1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pjp/images/Image(143).jpg"))); // NOI18N
        getContentPane().add(lblBullet1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 670, 10, 10));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pjp/images/back.png"))); // NOI18N
        back.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                backKeyPressed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 0, 1070, 700));

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("PLAY");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_backKeyPressed

    }//GEN-LAST:event_backKeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        System.out.println(evt.getKeyCode());
        int y=evt.getKeyCode();
        switch(y){
            case 37:
                lblTank.setBounds(lblTank.getX()-5,lblTank.getY(),lblTank.getWidth(),lblTank.getHeight());
                lblbullet.setBounds(lblbullet.getX()-5,lblbullet.getY(),lblbullet.getWidth(),lblbullet.getHeight());
                lblBullet1.setBounds(lblBullet1.getX()-5,lblBullet1.getY(),lblBullet1.getWidth(),lblBullet1.getHeight());break;
            case 39:
                lblTank.setBounds(lblTank.getX()+5,lblTank.getY(),lblTank.getWidth(),lblTank.getHeight());
                lblbullet.setBounds(lblbullet.getX()+5,lblbullet.getY(),lblbullet.getWidth(),lblbullet.getHeight());
                lblBullet1.setBounds(lblBullet1.getX()+5,lblBullet1.getY(),lblBullet1.getWidth(),lblBullet1.getHeight());break;
            case 65:

            new Thread(new Runnable() {

            public void run() {
                for(int i=lblbullet.getY();i<getHeight();i--){
                    lblbullet.setLocation(lblbullet.getX(),i);
                    try {
                        Thread.sleep(10);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(game.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }).start();

        //Bullet2

        new Thread(new Runnable() {

            public void run() {
                for(int i=lblBullet1.getY();i<getHeight();i--){
                    try {
                        lblBullet1.setLocation(lblBullet1.getX(), i);
                        Thread.sleep(20);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(game.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }).start();

// Tank 2----------
       /*lblT2.setVisible(true);
        
           new Thread(new Runnable() {

            public void run() {
                for(int a=lblT2.getX();a<getWidth();a--){
                    try {
                        lblT2.setLocation(a, lblT2.getY());
                        Thread.sleep(200);
                        try {
                            Thread.sleep(200);
                        } catch (InterruptedException ex) {
                            Logger.getLogger(game.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    } catch (InterruptedException ex) {
                        Logger.getLogger(game.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }).start(); */


        }
    }//GEN-LAST:event_formKeyPressed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
      
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel lblBullet1;
    private javax.swing.JLabel lblT1;
    private javax.swing.JLabel lblT2;
    private javax.swing.JLabel lblT3;
    private javax.swing.JLabel lblTank;
    private javax.swing.JLabel lblbullet;
    // End of variables declaration//GEN-END:variables

}
