/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CarGame.java
 *
 * Created on Oct 5, 2011, 4:56:57 PM
 */

package carex;

/**
 *
 * @author Nadun
 */
public class CarGame extends javax.swing.JFrame {

    boolean crashed= false;
    int speed = 0;
    /** Creates new form CarGame */
    public CarGame() {
        initComponents();
        Runnable r = new Runnable() {

            public void run() {
                
                while(!crashed){
                    if(lblRoad.getY() >= 600){
                        lblRoad.setLocation(lblRoad.getX(), lblRoad1.getY()-600);

                    }

                    if(lblRoad1.getY() >= 600){
                        lblRoad1.setLocation(lblRoad1.getX(), lblRoad.getY()-600);

                    }
                    lblRoad.setLocation(lblRoad.getX(), lblRoad.getY()+speed);
                    lblRoad1.setLocation(lblRoad1.getX(), lblRoad1.getY()+speed);
                    try {
                        Thread.sleep(100);
                    } catch (Exception e) {
                    }
                }
                
            }
        };
        Thread t = new Thread(r);
        t.start();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCar = new javax.swing.JLabel();
        lblRoad = new javax.swing.JLabel();
        lblRoad1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carex/car.png"))); // NOI18N
        getContentPane().add(lblCar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 380, 80, 150));

        lblRoad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carex/road.png"))); // NOI18N
        getContentPane().add(lblRoad, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        lblRoad1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carex/road.png"))); // NOI18N
        getContentPane().add(lblRoad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -600, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        int key = evt.getKeyCode();
        switch(key){
            case 37:lblCar.setLocation(lblCar.getX()-5, lblCar.getY());
            if(lblCar.getX()<300){
                crashed = true;
                lblCar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carex/car-crashed.png")));
            }
            break;
            case 38:
                    speed++;
//                lblRoad.setLocation(lblRoad.getX(), lblRoad.getY()+5);
//                lblRoad1.setLocation(lblRoad1.getX(), lblRoad1.getY()+5);
                break;
            case 39:lblCar.setLocation(lblCar.getX()+5, lblCar.getY());

            break;
            case 40:
                speed--;
                break;
        }
    }//GEN-LAST:event_formKeyPressed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblCar;
    private javax.swing.JLabel lblRoad;
    private javax.swing.JLabel lblRoad1;
    // End of variables declaration//GEN-END:variables

}
