/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AirFighterGame.java
 *
 * Created on Jan 19, 2011, 8:15:13 PM
 */

package airfighter;
/**
 *
 * @author Lakmal
 */
public class AirFighterGame extends javax.swing.JFrame {
       
    /** Creates new form AirFighterGame */
    public AirFighterGame() {
        initComponents();
         new Thread(new Runnable() {

            public void run() {
                while(true){
                   for(int i=jLabel2.getY();i<getHeight()/*-jLabel2.getHeight()*/;i++){
                    jLabel2.setLocation(jLabel2.getX(), i);
                    try {
                        Thread.sleep(100);
                    } catch (InterruptedException ex) {
                      ex.printStackTrace();
                    }
                }
            }
            }
        }).start();



    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblCar1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airfighter/car.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 130, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airfighter/road2.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, -30, 670, 580));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airfighter/car.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 180, -1, -1));

        lblCar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airfighter/car.png"))); // NOI18N
        getContentPane().add(lblCar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 200, -1, 160));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AirFighterGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblCar1;
    // End of variables declaration//GEN-END:variables

}
