/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.company.system.view;

import java.awt.BorderLayout;
import java.awt.ComponentOrientation;
import javax.swing.JOptionPane;

/**
 *
 * @author KASUN
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MaiWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainWindowPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mItemCustomer = new javax.swing.JMenuItem();
        mItemCoordinator = new javax.swing.JMenuItem();
        mItemAgent = new javax.swing.JMenuItem();
        mItemCountry = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout MainWindowPanelLayout = new javax.swing.GroupLayout(MainWindowPanel);
        MainWindowPanel.setLayout(MainWindowPanelLayout);
        MainWindowPanelLayout.setHorizontalGroup(
            MainWindowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 795, Short.MAX_VALUE)
        );
        MainWindowPanelLayout.setVerticalGroup(
            MainWindowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 524, Short.MAX_VALUE)
        );

        jMenu1.setText("File");

        mItemCustomer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_MASK));
        mItemCustomer.setText("Customer");
        mItemCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemCustomerActionPerformed(evt);
            }
        });
        jMenu1.add(mItemCustomer);

        mItemCoordinator.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_MASK));
        mItemCoordinator.setText("Coordinator");
        mItemCoordinator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemCoordinatorActionPerformed(evt);
            }
        });
        jMenu1.add(mItemCoordinator);

        mItemAgent.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.CTRL_MASK));
        mItemAgent.setText("Agent");
        mItemAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemAgentActionPerformed(evt);
            }
        });
        jMenu1.add(mItemAgent);

        mItemCountry.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.CTRL_MASK));
        mItemCountry.setText("Country");
        mItemCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemCountryActionPerformed(evt);
            }
        });
        jMenu1.add(mItemCountry);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainWindowPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainWindowPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mItemCoordinatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemCoordinatorActionPerformed
        // TODO add your handling code here:
        EmployeeView employeeView = new EmployeeView();
        MainWindowPanel.removeAll();
        MainWindowPanel.setLayout(new BorderLayout());
        MainWindowPanel.add(employeeView);
        MainWindowPanel.validate();
    }//GEN-LAST:event_mItemCoordinatorActionPerformed

    private void mItemCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemCountryActionPerformed
        // TODO add your handling code here:
        CountryView countryView = new CountryView();
        MainWindowPanel.removeAll();
        MainWindowPanel.setLayout(new BorderLayout());
        MainWindowPanel.add(countryView);
        MainWindowPanel.validate();
    }//GEN-LAST:event_mItemCountryActionPerformed

    private void mItemAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemAgentActionPerformed
        // TODO add your handling code here:
        AgentView agentView = new AgentView();
        MainWindowPanel.removeAll();
        MainWindowPanel.setLayout(new BorderLayout());
        MainWindowPanel.add(agentView);
        MainWindowPanel.validate();
    }//GEN-LAST:event_mItemAgentActionPerformed

    private void mItemCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemCustomerActionPerformed
        // TODO add your handling code here:
        CustomerView customerView = new CustomerView();
        MainWindowPanel.removeAll();
        MainWindowPanel.setLayout(new BorderLayout());
        MainWindowPanel.add(customerView);
        MainWindowPanel.validate();
    }//GEN-LAST:event_mItemCustomerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainWindowPanel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mItemAgent;
    private javax.swing.JMenuItem mItemCoordinator;
    private javax.swing.JMenuItem mItemCountry;
    private javax.swing.JMenuItem mItemCustomer;
    // End of variables declaration//GEN-END:variables
}
